ttttuuuoooo9999yuyuiiiiiiiiiiii
iiipppp12pppppyyywegrtyuyuiiiiiiiiiiii
ooouiuwegrtyuyuiiiiiiiiiiii
yyyiiipppp12pppppyyywegrtyuyuiiiiiiiiiiii
yyyooouiuwegrtyuyuiiiiiiiiiiii
mmmmoopp9999oooooo777yyyyttttyyyyyyyyypppp12pppppyyywegrtyuyuiiiiiiiiiiii
