ttttuuuoooo9999yuyuiiiiiiiiiiii
iiipppp12pppppyyywegrtyuyuiiiiiiiiiiii
ooouiuwegrtyuyuiiiiiiiiiiii
yyyiiipppp12pppppyyywegrtyuyuiiiiiiiiiiii
yyyooouiuwegrtyuyuiiiiiiiiiiii
oooooo777yyyyttttyyyyyyyyypppp12pppppyyywegrtyuyuiiiiiiiiiiii
